### ISSUE TITLE
download link issue

### ISSUE THREAD

**Issue by jeremy-cv** [sydney0zq/PTSNet#1]
Hi,

thanks for sharing your work. I'd like to try your pretrained network but I'm not able to access the given link : 
https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/25093814/X-152-32x8d-IN5k.pkl

**Comment by thzy236** [comment]
Me too!

**Comment by theodoruszq** [comment]
@jeremy-cv @thzy236  Sorry, this download link indeed has some problem. I will fix it soon.

**Comment by theodoruszq** [comment]
Hi all, this new download link on Google Drive has been updated. Please comment if you have any other issue.
