### ISSUE TITLE
非常感谢作者们的开源，在build.sh这里出了问题

### ISSUE THREAD

**Issue by shoutOutYangJie** [sydney0zq/PTSNet#2]
'vcc fatal   : Unsupported gpu architecture 'sm_50

这是我在bash build.sh这里出的错误。我把
![image](https://user-images.githubusercontent.com/46734514/60882921-6de65700-a27b-11e9-92aa-4ae90a7e1c89.png)
中的cuda文件夹改成了本机的cuda10.

**Comment by theodoruszq** [comment]
你好，这个可能和架构有关。如果你使用PyTorch1.0， 可以考虑使用`drsn/inplace_ABN`。这个不需要预先编译，它是动态编译的。
