### ISSUE TITLE
Something wrong with the pre-trained model

### ISSUE THREAD

**Issue by KunpengLi1994** [sydney0zq/PTSNet#5]
Thanks a lot for sharing the code! 

I meet the following error when trying to evaluate the pre-trained model on DAVIS2017:

![image](https://user-images.githubusercontent.com/16794194/60930768-c57cc680-a26b-11e9-823c-06eefbb63ebc.png)

It seems that there is problem about key mismatch. Could you please help to address this issue? Thanks!

**Comment by theodoruszq** [comment]
Sorry, this code has a long time. And I have made updates to solve these issues.

**Comment by theodoruszq** [comment]
And I have updated the InPlaceABN, if you use 0.4, you could use the `inplace_ABN_0.4`, otherwise the `inplace_ABN` for PyTorch 1.0.
