### ISSUE TITLE
unrecognized argument input size

### ISSUE THREAD

**Issue by ghost** [sydney0zq/PTSNet#8]
Hi again, 

the command i used to run training on the yvos dataset was the following:

CUDA_VISIBLE_DEVICES=0 python train.py --model_save_path experiments/snapshots --max_iters 100000 --decayat 60000 --learning_rate 2e-5 --batch_size 64 --input_size 256,256

and i recieved this output:

usage: train.py [-h] [--init_model_path INIT_MODEL_PATH]
                [--model_save_path MODEL_SAVE_PATH]
                [--img_size IMG_SIZE IMG_SIZE] [--batch_size BATCH_SIZE]
                [--save_num_images SAVE_NUM_IMAGES] [--decayat DECAYAT]
                [--learning_rate LEARNING_RATE [LEARNING_RATE ...]]
                [--learning_policy {step,poly,constant}]
                [--max_iters MAX_ITERS] [--save_iters SAVE_ITERS]
                [--weight_decay WEIGHT_DECAY] [--power POWER]
train.py: error: unrecognized arguments: --input_size 256,256

the argument "input_size" is one you suggest using in the readme file.
should i remove it from the command or add it to 'train.py'?

**Comment by theodoruszq** [comment]
Sorry it should be `img_size`, I usually use the default settings and I will fix it soon. https://github.com/sydney0zq/PTSNet/blob/e028efe07d263fb0951ad6bb67f8cb6dae749894/drsn/train.py#L54

**Comment by theodoruszq** [comment]
Fixed already. Closed.
