### ISSUE TITLE
init_model not found

### ISSUE THREAD

**Issue by ghost** [sydney0zq/PTSNet#9]
Hello,

I tried to train on the yvos dataset using the following command:
'CUDA_VISIBLE_DEVICES=0 python train.py --model_save_path experiments/snapshots --max_iters 100000 --decayat 60000 --learning_rate 2e-5 --batch_size 64'
(without inputting the input_size argument)

i received the following output:

"init_model_path": "init_models/resnet50-19c8e357.pth",
     "model_save_path": "experiments/snapshots",
     "img_size": [
      256,
      256
     ],
     "batch_size": 64,
     "save_num_images": 2,
     "decayat": 60000,
     "learning_rate": [
      2e-05
     ],
     "learning_policy": "step",
     "max_iters": 100000,
     "save_iters": 20000,
     "weight_decay": 0.0002,
     "power": 0.9
    }
[I 190807 14:22:30 train:127] Setting model...
Traceback (most recent call last):
  File "train.py", line 206, in <module>
    main()
  File "train.py", line 129, in main
    model.init(args.init_model_path, "yvos_train")
  File "/home/orel/projects/pts/PTSNet-master/drsn/model/drsn.py", line 216, in init
    saved_state_dict = torch.load(model_path)
  File "/home/orel/projects/pts/ptsenv/lib/python3.6/site-packages/torch/serialization.py", line 382, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'init_models/resnet50-19c8e357.pth'

I am guessing I needed to prepare the pretrained resnet model but i am not sure
could you instruct me on how to proceed?

Thanks!

**Comment by theodoruszq** [comment]
This 'init_models/resnet50-19c8e357.pth' can be obtained from the official PyTorch repo code: https://github.com/pytorch/vision/blob/master/torchvision/models/resnet.py. We could find the resnet50 pertained model can be downloaded from: https://download.pytorch.org/models/resnet50-19c8e357.pth.

**Comment by theodoruszq** [comment]
Closed. If you have any questions, please comment below.
